INSERT INTO TBL_CITY (FLD_ID, FLD_STORE_DATE, FLD_NAME) VALUES (1, '2011-09-06', 'not_specified');
INSERT INTO TBL_CITY (FLD_ID, FLD_STORE_DATE, FLD_NAME) VALUES (2, '2011-09-06', 'istanbul');
INSERT INTO TBL_CITY (FLD_ID, FLD_STORE_DATE, FLD_NAME) VALUES (3, '2011-09-06', 'ankara');
